# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 39fa7498e6b333e0fcbced9b88636d71d6425af694fd8aad426e0c450ab0f8b1330562f0ddc468ced2ac861ca7f0faeee2d00d022c37204e32dd2c199c0daea6

test:
  secret_key_base: 320da9874106e7526623944db261c601951885016029112520a50de3a14df4f6c89646ec33260971667128757e7b876cab2df9d53443f08d73df0a3afa1b5d36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
