# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9caa76f91773b1e6be1b46c0e9b66a8cc4eb0d620df983cc5cb61b429d0a5b7027baa3bbd61d2c827d75a3e1b13cd9195efed1216c4ddcba64a95a906e985876

test:
  secret_key_base: d33c9949875e0a0512cc53ed4c2435d3c192fa92f6a379bf99d351724f4ef71fa316ca24da436fd17d921dbdee5025d5bf6fcef9b532781736cd3d8e0002d017

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
